export const DummyConstant = {
  Countries: [
    'Afghanistan',
    'Albania',
    'Algeria',
    'American Samoa',
    'Andorra',
    'Angola',
    'Anguilla',
    'Antarctica',
    'Antigua and Barbuda',
    'Argentina',
    'Armenia',
    'Aruba',
    'Australia',
    'Austria',
    'Azerbaijan',
    'Bahamas (the)',
    'Bahrain',
    'Bangladesh',
    'Barbados',
    'Belarus',
    'Belgium',
    'Belize',
    'Benin',
    'Bermuda',
    'Bhutan',
    'Bolivia (Plurinational State of)',
    'Bonaire, Sint Eustatius and Saba',
    'Bosnia and Herzegovina',
    'Botswana',
    'Bouvet Island',
    'Brazil',
    'British Indian Ocean Territory (the)',
    'Brunei Darussalam',
    'Bulgaria',
    'Burkina Faso',
    'Burundi',
    'Cabo Verde',
    'Cambodia',
    'Cameroon',
    'Canada',
    'Cayman Islands (the)',
    'Central African Republic (the)',
    'Chad',
    'Chile',
    'China',
    'Christmas Island',
    'Cocos (Keeling) Islands (the)',
    'Colombia',
    'Comoros (the)',
    'Congo (the Democratic Republic of the)',
    'Congo (the)',
    'Cook Islands (the)',
    'Costa Rica',
    'Croatia',
    'Cuba',
    'Curaçao',
    'Cyprus',
    'Czechia',
    'Côte d"Ivoire',
    'Denmark',
    'Djibouti',
    'Dominica',
    'Dominican Republic (the)',
    'Ecuador',
    'Egypt',
    'El Salvador',
    'Equatorial Guinea',
    'Eritrea',
    'Estonia',
    'Eswatini',
    'Ethiopia',
    'Falkland Islands (the) [Malvinas]',
    'Faroe Islands (the)',
    'Fiji',
    'Finland',
    'France',
    'French Guiana',
    'French Polynesia',
    'French Southern Territories (the)',
    'Gabon',
    'Gambia (the)',
    'Georgia',
    'Germany',
    'Ghana',
    'Gibraltar',
    'Greece',
    'Greenland',
    'Grenada',
    'Guadeloupe',
    'Guam',
    'Guatemala',
    'Guernsey',
    'Guinea',
    'Guinea-Bissau',
    'Guyana',
    'Haiti',
    'Heard Island and McDonald Islands',
    'Holy See (the)',
    'Honduras',
    'Hong Kong',
    'Hungary',
    'Iceland',
    'India',
    'Indonesia',
    'Iran (Islamic Republic of)',
    'Iraq',
    'Ireland',
    'Isle of Man',
    'Israel',
    'Italy',
    'Jamaica',
    'Japan',
    'Jersey',
    'Jordan',
    'Kazakhstan',
    'Kenya',
    'Kiribati',
    'Korea (the Democratic People"s Republic of)',
    'Korea (the Republic of)',
    'Kuwait',
    'Kyrgyzstan',
    'Lao People"s Democratic Republic (the)',
    'Latvia',
    'Lebanon',
    'Lesotho',
    'Liberia',
    'Libya',
    'Liechtenstein',
    'Lithuania',
    'Luxembourg',
    'Macao',
    'Madagascar',
    'Malawi',
    'Malaysia',
    'Maldives',
    'Mali',
    'Malta',
    'Marshall Islands (the)',
    'Martinique',
    'Mauritania',
    'Mauritius',
    'Mayotte',
    'Mexico',
    'Micronesia (Federated States of)',
    'Moldova (the Republic of)',
    'Monaco',
    'Mongolia',
    'Montenegro',
    'Montserrat',
    'Morocco',
    'Mozambique',
    'Myanmar',
    'Namibia',
    'Nauru',
    'Nepal',
    'Netherlands (the)',
    'New Caledonia',
    'New Zealand',
    'Nicaragua',
    'Niger (the)',
    'Nigeria',
    'Niue',
    'Norfolk Island',
    'Northern Mariana Islands (the)',
    'Norway',
    'Oman',
    'Pakistan',
    'Palau',
    'Palestine, State of',
    'Panama',
    'Papua New Guinea',
    'Paraguay',
    'Peru',
    'Philippines (the)',
    'Pitcairn',
    'Poland',
    'Portugal',
    'Puerto Rico',
    'Qatar',
    'Republic of North Macedonia',
    'Romania',
    'Russian Federation (the)',
    'Rwanda',
    'Réunion',
    'Saint Barthélemy',
    'Saint Helena, Ascension and Tristan da Cunha',
    'Saint Kitts and Nevis',
    'Saint Lucia',
    'Saint Martin (French part)',
    'Saint Pierre and Miquelon',
    'Saint Vincent and the Grenadines',
    'Samoa',
    'San Marino',
    'Sao Tome and Principe',
    'Saudi Arabia',
    'Senegal',
    'Serbia',
    'Seychelles',
    'Sierra Leone',
    'Singapore',
    'Sint Maarten (Dutch part)',
    'Slovakia',
    'Slovenia',
    'Solomon Islands',
    'Somalia',
    'South Africa',
    'South Georgia and the South Sandwich Islands',
    'South Sudan',
    'Spain',
    'Sri Lanka',
    'Sudan (the)',
    'Suriname',
    'Svalbard and Jan Mayen',
    'Sweden',
    'Switzerland',
    'Syrian Arab Republic',
    'Taiwan (Province of China)',
    'Tajikistan',
    'Tanzania, United Republic of',
    'Thailand',
    'Timor-Leste',
    'Togo',
    'Tokelau',
    'Tonga',
    'Trinidad and Tobago',
    'Tunisia',
    'Turkey',
    'Turkmenistan',
    'Turks and Caicos Islands (the)',
    'Tuvalu',
    'Uganda',
    'Ukraine',
    'United Arab Emirates (the)',
    'United Kingdom of Great Britain and Northern Ireland (the)',
    'United States Minor Outlying Islands (the)',
    'United States of America (the)',
    'Uruguay',
    'Uzbekistan',
    'Vanuatu',
    'Venezuela (Bolivarian Republic of)',
    'Viet Nam',
    'Virgin Islands (British)',
    'Virgin Islands (U.S.)',
    'Wallis and Futuna',
    'Western Sahara',
    'Yemen',
    'Zambia',
    'Zimbabwe',
    'Åland Islands'
  ],
  Position: ['Director', 'Secretary', 'Agent', 'Managing Director', 'Manager', 'Officer', 'Auditor', 'Public Accountant Employee', 'Chief Executive Officer', 'Member', 'Director under Section 17(3)(d) of the Accountants Act', 'Alternate director', 'Representative'],
  RiskRating: ['LOW', 'MEDIUM', 'HIGH'],
  Occupation: ['11110 - LEGISLATOR',
    '11121 - SENIOR GOVERNMENT OFFICIAL',
    '11122 - SENIOR STATUTORY BOARD OFFICIAL',
    '11140 - SENIOR OFFICIAL OF POLITICAL PARTY ORGANISATION',
    "11150 - SENIOR OFFICIAL OF EMPLOYERS, WORKERS' AND OTHER ECONOMIC-INTEREST ORGANISATION",
    '11160 - SENIOR OFFICIAL OF HUMANITARIAN AND OTHER SPECIAL-INTEREST ORGANISATION',
    '11201 - MANAGING DIRECTOR/CHIEF EXECUTIVE OFFICER',
    '11202 - COMPANY DIRECTOR',
    '11203 - CHIEF OPERATING OFFICER/GENERAL MANAGER',
    '12111 - BUDGETING AND FINANCIAL ACCOUNTING MANAGER (INCLUDING FINANCIAL CONTROLLER)',
    '12112 - ADMINISTRATION MANAGER',
    '12121 - PERSONNEL/HUMAN RESOURCE MANAGER',
    '12122 - INDUSTRIAL RELATIONS MANAGER',
    '12123 - TRAINING MANAGER',
    '12130 - POLICY AND PLANNING MANAGER',
    '12191 - PREMISES AND FACILITIES MAINTENANCE MANAGER (INCLUDING BUILDING SECURITY MANAGER)',
    '12192 - LANDSCAPE OPERATIONS MANAGER',
    '12193 - WORKING PROPRIETOR (BUSINESS SERVICES AND ADMINISTRATIVE SERVICES)',
    '12199 - OTHER BUSINESS SERVICES AND ADMINISTRATION MANAGERS N.E.C.',
    '12211 - SALES AND MARKETING MANAGER',
    '12212 - BUSINESS DEVELOPMENT MANAGER',
    '12220 - ADVERTISING/PUBLIC RELATIONS MANAGER',
    '12230 - RESEARCH AND DEVELOPMENT MANAGER',
    '12241 - CUSTOMER SERVICE MANAGER',
    '12242 - CALL CENTRE MANAGER',
    '13101 - PRODUCTION MANAGER IN AGRICULTURE AND FISHERIES',
    '13102 - WORKING PROPRIETOR (AGRICULTURE AND FISHERIES)',
    '13211 - MANUFACTURING PLANT/PRODUCTION MANAGER',
    '13212 - WORKING PROPRIETOR (MANUFACTURING)',
    '13231 - BUILDING AND CONSTRUCTION PROJECT MANAGER',
    '13232 - WORKING PROPRIETOR (CONSTRUCTION)',
    '13241 - SUPPLY AND DISTRIBUTION/LOGISTICS/WAREHOUSING MANAGER',
    '13242 - PROCUREMENT/PURCHASING MANAGER',
    '13243 - TRANSPORT OPERATIONS MANAGER',
    '13244 - POSTAL SERVICE MANAGER',
    '13245 - WORKING PROPRIETOR (TRANSPORT, STORAGE AND COURIER)',
    '13291 - TECHNICAL/ENGINEERING SERVICES MANAGER (EG SHIPYARD MANAGER)',
    '13292 - QUALITY ASSURANCE MANAGER',
    '13299 - OTHER PRODUCTION AND OPERATIONS MANAGERS N.E.C. (EG MINING MANAGER)',
    '13301 - CHIEF INFORMATION OFFICER/CHIEF TECHNOLOGY OFFICER/CHIEF SECURITY OFFICER',
    '13302 - SOFTWARE AND APPLICATIONS MANAGER',
    '13303 - NETWORK AND COMMUNICATIONS MANAGER',
    '13304 - IT SERVICE MANAGER',
    '13305 - WORKING PROPRIETOR (INFORMATION AND COMMUNICATIONS TECHNOLOGY SERVICE)',
    '13410 - CHILD CARE SERVICES MANAGER',
    '13420 - HEALTH SERVICES MANAGER',
    '13430 - AGED CARE SERVICES MANAGER',
    '13440 - SOCIAL WELFARE MANAGER',
    '13451 - SCHOOL PRINCIPAL',
    '13459 - OTHER EDUCATION MANAGERS (INCLUDING REGISTRARS, DEANS OF EDUCATION INSTITUTIONS AND HEADS OF TRAINING INSTITUTIONS)',
    '13460 - FINANCIAL/INSURANCE SERVICES MANAGER (EG FINANCIAL INSTITUTION BRANCH MANAGER)',
    '13491 - WORKING PROPRIETOR (PROFESSIONAL, FINANCIAL, COMMUNITY AND SOCIAL SERVICES)',
    '13499 - OTHER PROFESSIONAL, FINANCIAL, COMMUNITY AND SOCIAL SERVICES MANAGERS',
    '14111 - HOTEL OPERATIONS/LODGING SERVICES MANAGER',
    '14112 - WORKING PROPRIETOR (LODGING SERVICES)',
    '14121 - RESTAURANT MANAGER',
    '14122 - CATERING SERVICES MANAGER',
    '14123 - WORKING PROPRIETOR (RESTAURANT AND OTHER CATERING SERVICES)',
    '14201 - RETAIL/SHOP SALES MANAGER',
    '14202 - WHOLESALE TRADE MANAGER',
    '14203 - WORKING PROPRIETOR (RETAIL TRADE)',
    '14204 - WORKING PROPRIETOR (WHOLESALE TRADE)',
    '14310 - SPORTS CENTRE MANAGER',
    '14321 - CASINO OPERATIONS MANAGER',
    '14322 - AMUSEMENT/THEME PARK MANAGER',
    '14323 - CINEMA MANAGER',
    '14324 - PARK/GARDEN/NATURE RESERVE MANAGER',
    '14325 - DISCOTHEQUE/KARAOKE/NIGHTCLUB MANAGER',
    '14326 - WELLNESS CENTRE MANAGER (EG HAIR/BEAUTY/SLIMMING/SPA/MANICURE/ MASSAGE)',
    '14327 - COMMUNITY/COUNTRY CLUB MANAGER',
    '14329 - OTHER RECREATION CENTRE MANAGERS',
    '14330 - ARTS AND CULTURAL CENTRE MANAGER (INCLUDING GALLERY AND MUSEUM MANAGER)',
    '14391 - WORKING PROPRIETOR (SPORTS, RECREATION, ARTS AND OTHER SERVICES)',
    '14392 - TRAVEL AGENCY MANAGER',
    '14399 - OTHER SERVICES MANAGERS N.E.C.',
    '21110 - PHYSICIST/ASTRONOMER',
    '21120 - METEOROLOGIST',
    '21130 - CHEMIST'],
  AppointmentStatus: ['Active', 'Withdrawn', null],
  EntityType: ['BIZ', 'COM', 'LLP', 'LP', 'PAF', 'UF', 'UL'],
  EntityStatus: ['Cancelled (Non-Renewal)', 'Live Company', 'Ceased Registration', 'Cancelled', 'Gazetted To Be Struck Off'],
  CompanyType: ['EXEMPT PRIVATE COMPANY LIMITED BY SHARES', 'PRIVATE COMPANY LIMITED BY SHARES', 'PUBLIC COMPANY LIMITED BY GUARANTEE', 'PUBLIC COMPANY LIMITED BY SHARES'],
  DocumentIDType: ['NRIC', 'FIN', 'Passport', 'Driver License', 'Power of Attorney', 'Proof of Address', 'Others'],
  SourceOfFunds: ['Salary', 'Personal Savings', 'Personal Wealth', 'Retirement Funds', 'Business Owner/Shareholder', 'Loan Facility', 'Personal Account'],
  NiumProductType: ['Send', 'Receive', 'Cards'],
  ProgramType: ['PROGRAM MANAGER', 'SME'],
  BusinessEntityType: ['Director', 'Ultimate Beneificial Owner', 'Shareholder', 'Authorized Signatory', 'Authorised Representative', 'Protector', 'Partner', 'REPRESENTATIVE'],
  GenderType: ['Male', 'Female'],
  CountryISO2Letter: ['US', 'SG', 'MY'],
  CountryISO3Letter: ['USA', 'SGP', 'MYS'],
  CurrencyISO3Letter: ['USD', 'SGD', 'MYR'],
  RoutingCodeType: ['SWIFT', 'IFSC', 'SORT CODE', 'ACH CODE', 'BRANCH CODE', 'BSB CODE', 'BANK CODE'],
  PaymentMethod: ['LOCAL', 'SWIFT', 'WALLET', 'CARD', 'PROXY'],
  CountryName: ['United States', 'Singapore', 'Malaysia'],
  IntendUseOfCardType: ['Consumer Ecommerce Payments', 'Company paying Digital Suppliers', 'Corporate T&E', 'Others'],
  CardProgramType: ['Virtual Only', 'Physical and Digital', 'Physical Only'],
  UnregulatedTrustType: ['FamilyTrust', 'CharitableTrust', 'TestamentaryTrust', 'UnitTrust', 'Other'],
  RegulatedTrustType: ['ASIC', 'MIS', 'Regulated Under Commonwealth Statutory Regulator', 'Government Superannuation Fund'],
  LegislationType: ['Established Under Commonwealth Legislation', 'Established Under State Territory Legislation', 'Other'],
  ListedExchange: ['Domestic Exchange', 'International Exchange', 'Not Listed'],
  BusinessType: ['Sole Trader', 'Private Limited Company', 'Public Company', 'Partnership', 'Limited Liability Partnership Firm', 'Others'],
  NiumFileFormat: ['jpg', 'jpeg', 'png', 'pdf', 'image/jpg', 'image/jpeg', 'image/png', 'application/pdf'],
  NiumDocumentTypesForBusiness: ['Business Registration Doc',
    'Trust Deed',
    'Partnership Deed',
    'Association Deed',
    'Register of Directors',
    'Register of Shareholders',
    'Proof of Existence',
    'LOA'],
  AdditionalInfoPosition: ['CAPTAIN', 'SEAFARER', 'SMC', 'VESSEL'],
  NiumKYBDocumentType: ['Business Registration Doc', 'Trust Deed', 'Partnership Deed', 'Association Deed', 'Register of Directors', 'Register of Shareholders'],
  CardThemeColor: ['DEFAULT', 'BLUE', 'ORANGE'],
  CardStatus: ['ACTIVE', 'FROZEN'],
  CoaOrganization: ['Advertising & Marketing', 'Bank fees', 'Cost of goods sold / Inventory', 'Employee Welfare', 'Loan', 'Local Transport', 'Meals and Entertainment', 'Office Expenses', 'Other Income']
};

export function noop() {}
