const niumWebhookEventList = {
  // CARD_CLIENT_SETUP: 'CARD_CLIENT_SETUP',
  CARD_CLIENT_KYB_STATUS_WEBHOOK: 'CARD_CLIENT_KYB_STATUS_WEBHOOK',
  CARD_CUSTOMER_REGISTRATION_WEBHOOK: 'CARD_CUSTOMER_REGISTRATION_WEBHOOK',
  //  CARD_REFUND_APPROVAL_WEBHOOK: 'CARD_REFUND_APPROVAL_WEBHOOK',
  //  CARD_ADD_CARD_WEBHOOK: 'CARD_ADD_CARD_WEBHOOK',
  //  CARD_ASSIGN_CARD_WEBHOOK: 'CARD_ASSIGN_CARD_WEBHOOK',
  //  CARD_ADD_ON_CARD_WEBHOOK: 'CARD_ADD_ON_CARD_WEBHOOK',
  //  CARD_ACTIVATION_CARD_WEBHOOK: 'CARD_ACTIVATION_CARD_WEBHOOK',
  //  // ^ theres more, we need to discuss first which one we need
  //
  //  CARD_CUSTOMER_REGISTRATION_WEBHOOK: 'CARD_CUSTOMER_REGISTRATION_WEBHOOK',
  //  CARD_CUSTOMER_UPDATE_WEBHOOK: 'CARD_CUSTOMER_UPDATE_WEBHOOK',

  // TODO:  still focused in transaction hooks
  // Transaction
  REMIT_TRANSACTION_INITIATED_WEBHOOK: 'REMIT_TRANSACTION_INITIATED_WEBHOOK',
  REMIT_TRANSACTION_REJECTED_WEBHOOK: 'REMIT_TRANSACTION_REJECTED_WEBHOOK',
  REMIT_TRANSACTION_CANCELLED_WEBHOOK: 'REMIT_TRANSACTION_CANCELLED_WEBHOOK',
  REMIT_TRANSACTION_RETURNED_WEBHOOK: 'REMIT_TRANSACTION_RETURNED_WEBHOOK',
  REMIT_TRANSACTION_PAID_WEBHOOK: 'REMIT_TRANSACTION_PAID_WEBHOOK',
  REMIT_TRANSACTION_SENT_TO_BANK_WEBHOOK: 'REMIT_TRANSACTION_SENT_TO_BANK_WEBHOOK',
  CARD_WALLET_FUNDING_WEBHOOK: 'CARD_WALLET_FUNDING_WEBHOOK',
  // Virtual Account Assigned
  VIRTUAL_ACCOUNT_ASSIGNED_WEBHOOK: 'VIRTUAL_ACCOUNT_ASSIGNED_WEBHOOK',
  VIRTUAL_ACCOUNT_ASSIGNMENT_FAILED_WEBHOOK: 'VIRTUAL_ACCOUNT_ASSIGNMENT_FAILED_WEBHOOK',
  // CARD
  CARD_POS_APPROVED_WEBHOOK: 'CARD_POS_APPROVED_WEBHOOK',
  CARD_TRANSACTION_REVERSAL_WEBHOOK: 'CARD_TRANSACTION_REVERSAL_WEBHOOK',
  CARD_SETTLEMENT_DIRECT_DEBIT_WEBHOOK: 'CARD_SETTLEMENT_DIRECT_DEBIT_WEBHOOK',
  CARD_SETTLEMENT_REVERSAL_WEBHOOK: 'CARD_SETTLEMENT_REVERSAL_WEBHOOK',
  CARD_EXPIRED_CARD_WEBHOOK: 'CARD_EXPIRED_CARD_WEBHOOK',
  CARD_TRANSACTION_LIMIT_EXCEEDS_WEBHOOK: 'CARD_TRANSACTION_LIMIT_EXCEEDS_WEBHOOK',
  CARD_INSUFFICIENT_FUNDS_DECLINED_CLIENT_WEBHOOK: 'CARD_INSUFFICIENT_FUNDS_DECLINED_CLIENT_WEBHOOK',
  CARD_RESTRICTED_TRANSACTIONS_WEBHOOK: 'CARD_RESTRICTED_TRANSACTIONS_WEBHOOK',
  CARD_TRANSACTION_NOT_SUPPORTED_WEBHOOK: 'CARD_TRANSACTION_NOT_SUPPORTED_WEBHOOK',
  CARD_MISC_WEBHOOK: 'CARD_MISC_WEBHOOK'
};

export default niumWebhookEventList;
