export const KYB_COMPLIANCE_STATUS = {
  INITIATED: 'INITITATED',
  IN_PROGRESS: 'IN_PROGRESS',
  ACTION_REQUIRED: 'ACTION_REQUIRED',
  RFI_REQUESTED: 'RFI_REQUESTED',
  RFI_RESPONDED: 'RFI_RESPONDED',
  COMPLETED: 'COMPLETED',
  REJECT: 'REJECT',
  ERROR: 'ERROR',
  EXPIRED: 'EXPIRED',
  CLOSED: 'CLOSED'
};

export const KYC_STATUS = {
  PENDING: 'Pending',
  CLEAR: 'Clear',
  FAILED: 'Failed',
  SUSPENDED: 'Suspended',
  BLOCKED: 'Blocked'
};

export const TRANSACTION_STATUS = {
  PENDING: 'PENDING',
  APPROVED: 'APPROVED',
  REVERSAL: 'REVERSAL',
  BLOCKED: 'BLOCKED',
  DECLINED: 'DECLINED'
};

export const TRANSACTION_COMPLIENCE_STATUS = {
  IN_PROGRESS: 'IN_PROGRESS',
  ACTION_REQUIRED: 'ACTION_REQUIRED',
  RFI_REQUESTED: 'RFI_REQUESTED',
  COMPLETED: 'COMPLETED',
  REJECTED: 'REJECTED'
};

export const REMITTANCE_STATUS = {
  PG_PROCESSING: 'PG_PROCESSING',
  SENT_TO_BANK: 'SENT_TO_BANK',
  RETURNED: 'RETURNED',
  PAID: 'PAID'
};

export const GRO_STATUS = {
  DRAFT: 'Draft',
  PENDING: 'Pending',
  RFI_REQUESTED: 'RFI Requested',
  COMPLETED: 'Completed',
  REJECTED: 'Rejected'
};
